// <auto-generated />
using System;
using LG__Lorem_Ipsum_Inc_Projetos.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackEnd_ProjetosLG.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210627130420_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("LG__Lorem_Ipsum_Inc_Projetos.Models.Participante", b =>
                {
                    b.Property<int>("ParticipanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ParticipanteId");

                    b.ToTable("Participantes");
                });

            modelBuilder.Entity("LG__Lorem_Ipsum_Inc_Projetos.Models.ParticipanteProjeto", b =>
                {
                    b.Property<int>("ParticipantePojetoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ParticipanteId")
                        .HasColumnType("int");

                    b.Property<int>("ProjetoId")
                        .HasColumnType("int");

                    b.HasKey("ParticipantePojetoId");

                    b.HasIndex("ParticipanteId");

                    b.HasIndex("ProjetoId");

                    b.ToTable("ParticipanteProjeto");
                });

            modelBuilder.Entity("LG__Lorem_Ipsum_Inc_Projetos.Models.Projeto", b =>
                {
                    b.Property<int>("ProjetoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Risco")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorProjeto")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("ProjetoId");

                    b.ToTable("Projetos");
                });

            modelBuilder.Entity("LG__Lorem_Ipsum_Inc_Projetos.Models.ParticipanteProjeto", b =>
                {
                    b.HasOne("LG__Lorem_Ipsum_Inc_Projetos.Models.Participante", "Participante")
                        .WithMany("ParticipanteProjeto")
                        .HasForeignKey("ParticipanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LG__Lorem_Ipsum_Inc_Projetos.Models.Projeto", "Projeto")
                        .WithMany("ParticipanteProjeto")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participante");

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("LG__Lorem_Ipsum_Inc_Projetos.Models.Participante", b =>
                {
                    b.Navigation("ParticipanteProjeto");
                });

            modelBuilder.Entity("LG__Lorem_Ipsum_Inc_Projetos.Models.Projeto", b =>
                {
                    b.Navigation("ParticipanteProjeto");
                });
#pragma warning restore 612, 618
        }
    }
}
